# DEVELOPMENT
version: '3'
services:
  project:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: ${LOCAL_IP}
      NODE_ENV: ${NODE_ENV}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - '3000:3000'
      - '4001:4001'
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    command: bash -c "sleep infinity"
  db:
    image: postgres:13.1-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: werwer
      POSTGRES_USER: postgres
      POSTGRES_DB: sandbox_1_dev
    ports:
      - '5432:5432'
