# DEVELOPMENT
version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      args:
        PORT: 4001
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
      - DB_USERNAME=postgres
      - DB_NAME=sandbox_1_dev
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - '4001:4001'
    entrypoint: ['/bin/bash', 'docker-entrypoint-dev.sh']
  db:
    image: postgres:13.1-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: werwer
      POSTGRES_USER: postgres
      POSTGRES_DB: sandbox_1_dev
    ports:
      - '5432:5432'
