
version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn build
      - run: yarn netlify:deploy

# version: 2.1
# jobs:
#   run-tests:
#     docker:
#       - image: circleci/node:10
#     steps:
#       - checkout
#       - run:
#         name: asdf
#         command: |
#           npm install --save
#       - run:
#         name: Run Unit tests
#         command: |
#           npm run test
#       - store_test_results:
#           path: test-results
#       - store_artifacts:
#           path: test-results
# workflows:
#   build_test:
#     jobs:
#       - run tests
