export const commentsConstants = {
  GET_COMMENT_REQUEST: 'GET_COMMENT_REQUEST',
  GET_COMMENT_SUCCESS: 'GET_COMMENT_SUCCESS',
  GET_COMMENT_FAILURE: 'GET_COMMENT_FAILURE',

  GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST',
  GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
  GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',

  CREATE_COMMENT_REQUEST: 'CREATE_COMMENT_REQUEST',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE',

  UPDATE_COMMENT_REQUEST: 'UPDATE_COMMENT_REQUEST',
  UPDATE_COMMENT_SUCCESS: 'UPDATE_COMMENT_SUCCESS',
  UPDATE_COMMENT_FAILURE: 'UPDATE_COMMENT_FAILURE',

  DESTROY_COMMENT_REQUEST: 'DESTROY_COMMENT_REQUEST',
  DESTROY_COMMENT_SUCCESS: 'DESTROY_COMMENT_SUCCESS',
  DESTROY_COMMENT_FAILURE: 'DESTROY_COMMENT_FAILURE',
};
