export const sessionConstants = {
  GET_SESSION_REQUEST: 'GET_SESSION_REQUEST',
  GET_SESSION_SUCCESS: 'GET_SESSION_SUCCESS',
  GET_SESSION_FAILED: 'GET_SESSION_FAILED',

  CREATE_SESSION_REQUEST: 'CREATE_SESSION_REQUEST',
  CREATE_SESSION_SUCCESS: 'CREATE_SESSION_SUCCESS',
  CREATE_SESSION_FAILED: 'CREATE_SESSION_FAILED',

  DESTROY_SESSION_REQUEST: 'DESTROY_SESSION_REQUEST',
  DESTROY_SESSION_SUCCESS: 'DESTROY_SESSION_SUCCESS',
  DESTROY_SESSION_FAILED: 'DESTROY_SESSION_FAILED',
};
