export const sessionConstants = {
  GET_SESSION_REQUEST: 'GET_SESSION_REQUEST',
  GET_SESSION_SUCCESS: 'GET_SESSION_SUCCESS',
  GET_SESSION_FAILURE: 'GET_SESSION_FAILURE',

  CREATE_SESSION_REQUEST: 'CREATE_SESSION_REQUEST',
  CREATE_SESSION_SUCCESS: 'CREATE_SESSION_SUCCESS',
  CREATE_SESSION_FAILURE: 'CREATE_SESSION_FAILURE',

  DESTROY_SESSION_REQUEST: 'DESTROY_SESSION_REQUEST',
  DESTROY_SESSION_SUCCESS: 'DESTROY_SESSION_SUCCESS',
  DESTROY_SESSION_FAILURE: 'DESTROY_SESSION_FAILURE',
};
