env:
  browser: true
  es2021: true
extends:
  - airbnb-typescript/base
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
rules:
  {
    no-console: 1,
    prettier/prettier: 1,
    no-unused-vars: 1,
    no-param-reassign: 0,
    require-jsdoc: "off",
    object-shorthand: "off",
    new-cap: "off",
    camelcase: "off",
    import/prefer-default-export: "off",
    class-methods-use-this: "off",
    max-classes-per-file: "off",
    no-plusplus: "off",
    "@typescript-eslint/no-unused-vars": "off",
    no-restricted-syntax: "off",
    no-continue: "off",
    # curly: ["warn", "multi"],
    max-len: ["warn", { "code": 120}]
  }
