# DEVELOPMENT
version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - '4001:4001'
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_DB_NAME: ${DB_DB_NAME}
      DB_HOST: ${DB_HOST}
    command: bash -c 'sleep infinity'
  db:
    image: postgres:13.1-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DB_NAME}
    ports:
      - '5432:5432'
  redis:
    image: redis:6.2.5
    read_only: true
    user: redis
    ports:
      - '6379:6379'
