# DEVELOPMENT
version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    stdin_open: true
    command: npm run start
